# Generated by Django 5.0.7 on 2024-07-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='max_person',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubs',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name=range(1, 5)),
            preserve_default=False,
        ),
    ]
