# Generated by Django 5.0.7 on 2024-08-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_catalogue_max_person_clubs_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name=range(1, 5)),
        ),
    ]
