# Generated by Django 5.0.7 on 2024-08-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_bookings_booked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='availability',
            field=models.CharField(default='1111111', max_length=7),
            preserve_default=False,
        ),
    ]
