# Generated by Django 5.0.7 on 2024-08-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_clubs_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='club_photos/'),
        ),
    ]
