# Generated by Django 5.0.7 on 2024-09-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_bookings_reservation_name_customuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='comments',
            field=models.CharField(default='No comment', max_length=200),
        ),
    ]
