# Generated by Django 5.0.7 on 2024-09-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_bookings_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_type',
            field=models.CharField(default='000', max_length=3),
        ),
    ]
