# Generated by Django 5.0.7 on 2024-09-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_bookings_booking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='comments',
            field=models.TextField(default='No comment', max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
