# Generated by Django 5.0.7 on 2024-09-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_bookings_comments_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='not_available',
            field=models.CharField(default='', max_length=130),
        ),
    ]
