# Generated by Django 5.0.7 on 2024-09-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_clubs_not_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='photo',
            field=models.ImageField(blank=True, default='club_photos/Default_Club.jpg', null=True, upload_to='club_photos/'),
        ),
    ]
