# Generated by Django 5.0.7 on 2024-09-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_customuser_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='service_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Premium', 'Premium'), ('Special', 'Special')], max_length=10),
        ),
    ]
