# Generated by Django 5.0.7 on 2024-09-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_catalogue_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_type',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='comments',
            field=models.TextField(blank=True, default='No comment', max_length=200),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='not_available',
            field=models.CharField(blank=True, default='', max_length=130),
        ),
    ]
