# Generated by Django 5.0.7 on 2024-08-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='reservation_name',
            field=models.CharField(default='InputReservationName', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='user_photos/Default_User.jpg', null=True, upload_to='user_photos/'),
        ),
    ]
